---
- name: get dotfile playbook
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
 
  tasks:
    - name: get dotfiles from github...
      ansible.builtin.git:
        repo: 'https://github.com/draptik/dotfiles.git'
        dest: ~/.dotfiles

