---
- name: Jupyter Lab for RPi1
  hosts: grasshopper
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: pi
 
  tasks:
    - name: apt update...
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: apt upgrade...
      apt:
        upgrade: dist
    
    - name: apt install JupyterLab prerequisites...
      apt:
        pkg:
          - python3-pip
          - libffi-dev

    - name: pip install JupyterLab prerequisites...
      pip:
        name:
          - setuptools
          - cffi
          
    - name: pip install JupyterLab...
      pip:
        name:
          - jupyterlab

    - name: file: create folder for notebooks...
      file:
        path: /home/pi/notebooks
        state: directory
        owner: pi
        mode: 0755

    - name: copy: jupyter.service file to destination...
      copy:
        src: ./resources/jupyter.service
        dest: /etc/systemd/system/jupyter.service
        owner: root

    - name: systemd: enable and start jupyter service...
      systemd:
        name: jupyter
        enabled: yes
        daemon_reload: yes
        state: started
